#
#~/.bash_aliases
#

#Convenient aliases
alias e='emacs -nw'
alias sl='ls'
alias la='ls -a'
alias rmt='rm *~ && rm .*~'

#git
alias gits='git status -s'
alias gpl='git pull'
alias gp='git push'
alias gsl='git shortlog -sn'
alias gqs='git quick-stats'


#Color and such
alias gdb='gdb -q'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ip='ip -c'
